from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import time

import pandas as pd


STRUCTURAL_THEME_KEYWORDS = [
    "AI",
    "人工智能",
    "算力",
    "CPO",
    "光通信",
    "光模块",
    "数据中心",
    "半导体",
    "芯片",
    "机器人",
    "低空",
    "固态电池",
    "PCB",
    "铜缆",
    "先进封装",
]


@dataclass(frozen=True)
class BoardScoreDetail:
    name: str
    score: float
    reason: str


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Rank K-line candidates with concept, fund-flow, and persistence filters.")
    parser.add_argument("--candidates", required=True, help="CSV generated by K-line candidate scan")
    parser.add_argument("--output-dir", default="reports/kline_candidate_ranked")
    parser.add_argument("--top-n", type=int, default=10)
    parser.add_argument("--max-concepts", type=int, default=80, help="Maximum hot concepts to inspect for membership")
    parser.add_argument("--start-date", default="20250603", help="Concept persistence start date, YYYYMMDD")
    parser.add_argument("--end-date", default="20260603", help="Concept persistence end date, YYYYMMDD")
    parser.add_argument("--require-latest-date", action="store_true", help="Keep only candidates on the latest signal date in input")
    return parser


def main() -> None:
    args = build_parser().parse_args()
    output_paths = run(args)
    for path in output_paths:
        print(path)


def run(args: argparse.Namespace) -> list[Path]:
    candidates = pd.read_csv(args.candidates, dtype={"code": str})
    if candidates.empty:
        raise RuntimeError(f"candidate file is empty: {args.candidates}")
    candidates["code"] = candidates["code"].astype(str).str.zfill(6)
    if args.require_latest_date and "signal_date" in candidates:
        latest_signal_date = candidates["signal_date"].max()
        candidates = candidates[candidates["signal_date"] == latest_signal_date].reset_index(drop=True)

    board_scores, board_reasons, stock_to_boards, failures = fetch_live_context(
        candidate_codes=set(candidates["code"]),
        max_concepts=args.max_concepts,
        start_date=args.start_date,
        end_date=args.end_date,
    )
    ranked = rank_candidates(candidates, stock_to_boards, board_scores, board_reasons)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    ranked_path = output_dir / "ranked_candidates.csv"
    top_path = output_dir / f"top_{args.top_n}_candidates.csv"
    failures_path = output_dir / "context_failures.csv"
    summary_path = output_dir / "summary.md"

    ranked.to_csv(ranked_path, index=False, encoding="utf-8-sig")
    ranked.head(args.top_n).to_csv(top_path, index=False, encoding="utf-8-sig")
    pd.DataFrame(failures).to_csv(failures_path, index=False, encoding="utf-8-sig")
    summary_path.write_text(build_summary_markdown(ranked, args.top_n, failures), encoding="utf-8")
    return [ranked_path, top_path, failures_path, summary_path]


def normalize_series(values: pd.Series, higher_is_better: bool = True) -> pd.Series:
    series = pd.to_numeric(values, errors="coerce")
    if series.notna().sum() == 0:
        return pd.Series([0.0] * len(series), index=series.index)
    minimum = float(series.min())
    maximum = float(series.max())
    if maximum == minimum:
        return pd.Series([0.5] * len(series), index=series.index)
    normalized = (series - minimum) / (maximum - minimum)
    if not higher_is_better:
        normalized = 1 - normalized
    return normalized.fillna(0.0)


def theme_keyword_score(name: str) -> float:
    upper_name = str(name).upper()
    matches = sum(1 for keyword in STRUCTURAL_THEME_KEYWORDS if keyword.upper() in upper_name)
    return min(1.0, matches / 2.0)


def board_persistence_score(history: pd.DataFrame) -> float:
    if history.empty or "close" not in history:
        return 0.0
    close = pd.to_numeric(history["close"], errors="coerce").dropna()
    if len(close) < 40 or float(close.iloc[0]) <= 0:
        return 0.0

    one_year_return = float(close.iloc[-1]) / float(close.iloc[0]) - 1
    sixty_day_return = float(close.iloc[-1]) / float(close.iloc[-min(60, len(close))]) - 1
    ma60 = close.rolling(60).mean().iloc[-1] if len(close) >= 60 else close.mean()
    above_ma60 = 1.0 if float(close.iloc[-1]) > float(ma60) else 0.0
    positive_rate = float((close.pct_change().tail(min(60, len(close))).dropna() > 0).mean())

    one_year_component = _clip_scale(one_year_return, -0.20, 1.00)
    sixty_day_component = _clip_scale(sixty_day_return, -0.10, 0.50)
    return float(
        0.35 * one_year_component
        + 0.30 * sixty_day_component
        + 0.20 * above_ma60
        + 0.15 * positive_rate
    )


def rank_candidates(
    candidates: pd.DataFrame,
    stock_to_boards: dict[str, list[str]],
    board_scores: dict[str, float],
    board_reasons: dict[str, str],
) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    for _, row in candidates.iterrows():
        code = str(row.get("code", "")).zfill(6)
        matched = [name for name in stock_to_boards.get(code, []) if name in board_scores]
        matched_scores = sorted((board_scores[name] for name in matched), reverse=True)
        best_score = matched_scores[0] if matched_scores else 0.0
        average_top3 = sum(matched_scores[:3]) / min(3, len(matched_scores)) if matched_scores else 0.0
        breadth_bonus = min(0.10, 0.025 * len(matched))
        priority_score = 100 * (0.70 * best_score + 0.20 * average_top3 + breadth_bonus)

        output = row.to_dict()
        output["matched_hot_boards"] = "；".join(matched[:8])
        output["matched_board_count"] = len(matched)
        output["priority_score"] = round(priority_score, 2)
        output["priority_reason"] = _candidate_reason(matched, board_scores, board_reasons)
        rows.append(output)

    ranked = pd.DataFrame(rows)
    if ranked.empty:
        return ranked
    return ranked.sort_values(
        ["priority_score", "matched_board_count", "code"],
        ascending=[False, False, True],
        ignore_index=True,
    )


def fetch_live_context(
    candidate_codes: set[str],
    max_concepts: int,
    start_date: str,
    end_date: str,
) -> tuple[dict[str, float], dict[str, str], dict[str, list[str]], list[dict[str, str]]]:
    import akshare as ak
    from daily_sector_report import Board, fetch_board_cons

    failures: list[dict[str, str]] = []
    concept_names = _retry(lambda: ak.stock_board_concept_name_ths(), "stock_board_concept_name_ths", failures)
    if concept_names is None or concept_names.empty:
        return {}, {}, {}, failures
    concept_code_by_name = {
        str(row["name"]): str(row["code"])
        for _, row in concept_names.iterrows()
        if pd.notna(row.get("name")) and pd.notna(row.get("code"))
    }

    flow_frames = fetch_concept_flow_frames(ak, failures)
    hot_names = select_hot_concepts(flow_frames, max_concepts)
    recent_names = fetch_recent_concepts(ak, failures)
    hot_names = _dedupe_keep_order(hot_names + recent_names)[:max_concepts]
    hot_names = [name for name in hot_names if name in concept_code_by_name]

    board_scores, board_reasons = score_hot_boards(ak, hot_names, flow_frames, start_date, end_date, failures)
    stock_to_boards = map_stocks_to_hot_boards(
        hot_names,
        concept_code_by_name,
        candidate_codes,
        board_scores,
        fetch_board_cons,
        Board,
        failures,
    )
    return board_scores, board_reasons, stock_to_boards, failures


def fetch_concept_flow_frames(ak_module: object, failures: list[dict[str, str]]) -> dict[str, pd.DataFrame]:
    frames: dict[str, pd.DataFrame] = {}
    for symbol in ["即时", "3日排行", "5日排行", "10日排行"]:
        frame = _retry(lambda symbol=symbol: ak_module.stock_fund_flow_concept(symbol=symbol), f"stock_fund_flow_concept:{symbol}", failures)
        if frame is not None and not frame.empty:
            frames[symbol] = frame.copy()
    return frames


def select_hot_concepts(flow_frames: dict[str, pd.DataFrame], max_concepts: int) -> list[str]:
    names: list[str] = []
    for symbol in ["10日排行", "5日排行", "3日排行", "即时"]:
        frame = flow_frames.get(symbol)
        if frame is None or frame.empty:
            continue
        name_column = "行业" if "行业" in frame else frame.columns[1]
        for name in frame[name_column].astype(str).head(max(20, max_concepts // 2)):
            names.append(name)
    return _dedupe_keep_order(names)[:max_concepts]


def fetch_recent_concepts(ak_module: object, failures: list[dict[str, str]]) -> list[str]:
    summary = _retry(lambda: ak_module.stock_board_concept_summary_ths(), "stock_board_concept_summary_ths", failures)
    if summary is None or summary.empty or "概念名称" not in summary:
        return []
    return summary["概念名称"].astype(str).head(20).tolist()


def score_hot_boards(
    ak_module: object,
    names: list[str],
    flow_frames: dict[str, pd.DataFrame],
    start_date: str,
    end_date: str,
    failures: list[dict[str, str]],
) -> tuple[dict[str, float], dict[str, str]]:
    flow_scores, flow_reasons = score_flow_frames(flow_frames)
    scores: dict[str, float] = {}
    reasons: dict[str, str] = {}

    for name in names:
        history = _retry(
            lambda name=name: ak_module.stock_board_concept_index_ths(symbol=name, start_date=start_date, end_date=end_date),
            f"stock_board_concept_index_ths:{name}",
            failures,
            attempts=2,
            delay_seconds=0.4,
        )
        persistence = board_persistence_score(normalize_board_history(history)) if history is not None else 0.0
        flow_score = flow_scores.get(name, 0.0)
        keyword = theme_keyword_score(name)
        combined = 0.45 * flow_score + 0.40 * persistence + 0.15 * keyword
        scores[name] = round(float(combined), 4)
        reasons[name] = "; ".join(
            [
                f"资金热度{flow_score:.2f}",
                f"一年持续性{persistence:.2f}",
                f"主题加分{keyword:.2f}",
                flow_reasons.get(name, ""),
            ]
        ).strip("; ")
    return scores, reasons


def score_flow_frames(flow_frames: dict[str, pd.DataFrame]) -> tuple[dict[str, float], dict[str, str]]:
    scores: dict[str, float] = {}
    reasons: dict[str, list[str]] = {}
    weights = {"即时": 0.20, "3日排行": 0.20, "5日排行": 0.25, "10日排行": 0.35}

    for symbol, frame in flow_frames.items():
        if frame.empty:
            continue
        df = frame.copy().reset_index(drop=True)
        name_column = "行业" if "行业" in df else df.columns[1]
        df["_rank_score"] = 1 - (df.index / max(1, len(df) - 1))
        metric_columns = [column for column in ["净额", "阶段涨跌幅", "行业-涨跌幅"] if column in df]
        metric_score = pd.Series([0.0] * len(df), index=df.index)
        for column in metric_columns:
            metric_score += normalize_series(_numeric_column(df[column]))
        if metric_columns:
            metric_score = metric_score / len(metric_columns)
        df["_flow_score"] = 0.65 * df["_rank_score"] + 0.35 * metric_score
        weight = weights.get(symbol, 0.15)
        for _, row in df.iterrows():
            name = str(row[name_column])
            scores[name] = scores.get(name, 0.0) + weight * float(row["_flow_score"])
            reasons.setdefault(name, []).append(f"{symbol}排名{int(row.name) + 1}")

    return {name: min(1.0, score) for name, score in scores.items()}, {name: "；".join(items[:3]) for name, items in reasons.items()}


def normalize_board_history(history: pd.DataFrame | None) -> pd.DataFrame:
    if history is None or history.empty:
        return pd.DataFrame()
    mapping = {"日期": "date", "收盘价": "close", "成交量": "volume", "成交额": "amount"}
    df = history.rename(columns=mapping).copy()
    if "close" not in df:
        return pd.DataFrame()
    df["close"] = pd.to_numeric(df["close"], errors="coerce")
    if "volume" in df:
        df["volume"] = pd.to_numeric(df["volume"], errors="coerce")
    return df.dropna(subset=["close"]).reset_index(drop=True)


def map_stocks_to_hot_boards(
    hot_names: list[str],
    concept_code_by_name: dict[str, str],
    candidate_codes: set[str],
    board_scores: dict[str, float],
    fetch_board_cons,
    board_class,
    failures: list[dict[str, str]],
) -> dict[str, list[str]]:
    stock_to_boards: dict[str, list[str]] = {code: [] for code in candidate_codes}
    for name in hot_names:
        if name not in board_scores:
            continue
        board_code = concept_code_by_name.get(name)
        if not board_code:
            continue
        try:
            board = board_class(name, "concept", 0.0, {"_provider": "ths", "板块代码": board_code})
            members = fetch_board_cons(board)
            if members.empty or "代码" not in members:
                continue
            member_codes = set(members["代码"].astype(str).str.extract(r"(\d{6})", expand=False).dropna())
            for code in sorted(candidate_codes & member_codes):
                stock_to_boards.setdefault(code, []).append(name)
        except Exception as exc:
            failures.append({"source": f"fetch_board_cons:{name}", "reason": str(exc)[:220]})
        time.sleep(0.05)
    return stock_to_boards


def build_summary_markdown(ranked: pd.DataFrame, top_n: int, failures: list[dict[str, str]]) -> str:
    lines = [
        "# Ranked K-line Candidates",
        "",
        "## Method",
        "",
        "- Gate: original K-line candidate model remains unchanged.",
        "- Ranking: hot concept membership, recent concept fund flow, one-year concept persistence, and small structural-theme keyword bonus.",
        "- Purpose: reduce daily candidates to a smaller watchlist for retail execution.",
        "",
        "## Top Candidates",
        "",
    ]
    if ranked.empty:
        lines.append("No ranked candidates.")
    else:
        columns = ["code", "name", "priority_score", "matched_hot_boards", "priority_reason"]
        lines.append(ranked.head(top_n)[columns].to_markdown(index=False))
    lines.extend(
        [
            "",
            "## Data Issues",
            "",
            f"- context_failures: {len(failures)}",
        ]
    )
    return "\n".join(lines) + "\n"


def _candidate_reason(matched: list[str], board_scores: dict[str, float], board_reasons: dict[str, str]) -> str:
    if not matched:
        return "未匹配到本轮热门概念，保留K线信号但优先级降低"
    top = sorted(matched, key=lambda name: board_scores.get(name, 0.0), reverse=True)[:3]
    return "；".join(f"{name}({board_scores.get(name, 0.0):.2f}: {board_reasons.get(name, '')})" for name in top)


def _numeric_column(values: pd.Series) -> pd.Series:
    return pd.to_numeric(values.astype(str).str.replace("%", "", regex=False).str.replace(",", "", regex=False), errors="coerce")


def _clip_scale(value: float, low: float, high: float) -> float:
    if high == low:
        return 0.5
    return max(0.0, min(1.0, (float(value) - low) / (high - low)))


def _dedupe_keep_order(values: list[str]) -> list[str]:
    seen: set[str] = set()
    output: list[str] = []
    for value in values:
        text = str(value).strip()
        if text and text not in seen:
            output.append(text)
            seen.add(text)
    return output


def _retry(callable_, source: str, failures: list[dict[str, str]], attempts: int = 3, delay_seconds: float = 0.8):
    last_error: Exception | None = None
    for attempt in range(attempts):
        try:
            return callable_()
        except Exception as exc:
            last_error = exc
            time.sleep(delay_seconds * (attempt + 1))
    failures.append({"source": source, "reason": str(last_error)[:220] if last_error else "unknown"})
    return None


if __name__ == "__main__":
    main()
